language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vale-dynamic' ]; then cd .. && eval "mv $currentfolder generator-vale-dynamic" && cd generator-vale-dynamic; fi

